services:
    auto-booking-frontend:
        networks:
          - app-network
        container_name: auto-booking-frontend
        ports: 
          - "3000:3000"
        image: auto-booking-frontend
        build:
          context: ./
          dockerfile: Dockerfile.frontend
        environment:
          # For setupProxy.js when dev server runs in this container
          - REACT_APP_BACKEND_PROXY_TARGET=http://auto-booking-backend:4201
          - REACT_APP_BACKEND_URL=http://auto-booking-backend:4201
    auto-booking-backend:
        networks:
          - app-network
        container_name: auto-booking-backend
        ports: 
          - "4201:4201"
        image: auto-booking-backend
        build:
          context: ./
          dockerfile: Dockerfile.backend
networks:
  app-network:
    driver: bridge

    
    